apiVersion: monitor.azure.com/v1
kind: Instrumentation
metadata:
  name: default
  namespace: zava-shop
spec:
  settings:
    autoInstrumentationPlatforms: []
  destination: # required
    applicationInsightsConnectionString: ""
